subdir-ccflags-y   			+= -I$(BALONG_TOPDIR)/modem/include/drv/acore/
subdir-ccflags-y   			+= -I$(BALONG_TOPDIR)/modem/include/drv/common/
subdir-ccflags-y   			+= -I$(BALONG_TOPDIR)/modem/drv820/common/src/comm/inc/
subdir-ccflags-y   			+= -I$(BALONG_TOPDIR)/modem/drv820/hi6210/src/interface/inc/
subdir-ccflags-y   			+= -I$(BALONG_TOPDIR)/modem/include/nv/tl/drv/
subdir-ccflags-y   			+= -I$(BALONG_TOPDIR)/modem/include/nv/tl/oam/
subdir-ccflags-y   			+= -I$(BALONG_TOPDIR)/modem/include/nv/tl/lps/
subdir-ccflags-y   			+= -I$(BALONG_TOPDIR)/modem/include/phy/lphy/
subdir-ccflags-y   			+= -I$(BALONG_TOPDIR)/modem/config/nvim/include/gu/
subdir-ccflags-y   			+= -I$(BALONG_TOPDIR)/modem/config/product/$(OBB_PRODUCT_NAME)/config

obj-$(CONFIG_HISI_BALONG_MODEM_HI6XXX)	+= oam/ ps/ taf/
